[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson @ ^6.21.5
    rweather/Crypto
    links2004/WebSockets
build_flags =
    -D CONFIG_ASYNC_TCP_TASK_STACK_SIZE=8192
    -D ARDUINOJSON_ENABLE_ARDUINO_STRING=1